pub mod apps;
pub mod audit;
pub mod autostart;
pub mod big_files;
pub mod browser_cleanup;
pub mod dev_cache;
pub mod disk_health;
pub mod duplicates;
pub mod elevation;
pub mod executor;
pub mod file_ops;
pub mod leftovers;
pub mod models;
pub mod rules;
pub mod scanner;
pub mod snapshot;
pub mod tweaks;
pub mod vitals;
pub mod xray;

pub use apps::{AppManager, InstalledAppUsage};
pub use audit::AuditJournal;
pub use autostart::{AutostartItem, AutostartManager};
pub use big_files::{BigFileFinder, BigFileItem, BigFileQuery, BigFileReport};
pub use browser_cleanup::{BrowserCleanupReport, BrowserCleanupScanner, BrowserDataCategory, BrowserProfile};
pub use dev_cache::DevCacheCleaner;
pub use disk_health::{DiskHealthInfo, DiskHealthMonitor, DiskHealthReport, SmartAttribute};
pub use duplicates::{DuplicateFinder, DuplicateGroup, DuplicateItem};
pub use elevation::ElevationManager;
pub use executor::Executor;
pub use file_ops::{harden_path, move_paths_to_trash};
pub use leftovers::{AppLeftover, LeftoversScanner};
pub use models::*;
pub use rules::RuleEngine;
pub use scanner::Scanner;
pub use snapshot::SnapshotManager;
pub use tweaks::{LinuxTweaks, WindowsTweaks, detect_system_dns, set_system_dns};
pub use vitals::{DiskHealthSummary, SnapshotCompactorInfo, SystemVitals, SystemVitalsReport};
pub use xray::{SpaceXRay, XRayFileItem, XRayFolderNode, XRayReport};

